version: '3'
services:
  banking-app:
    build: ./
    tty: true
    command: sh -c "npm install && yarn add axios@0.19.2 bootstrap@4.4.1 history@4.10.1 jwt-decode@2.2.0 lodash@4.17.15 moment@2.25.3 node-sass@4.14.1 react-bootstrap@1.0.1 react-redux@7.2.0 react-router-dom@5.1.2 redux@4.0.5 redux-thunk@2.3.0 && yarn start"
    environment: 
      - NODE_ENV=development
      - PORT=3000
    environment: 
      POSTGRES_HOST: psql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank_account

    ports:
      - 3000:3000
    working_dir: /root/fullstack-banking-app
    volumes:
      - ./:/root/fullstack-banking-app:cached
  
  server:
    build: ./server
    # tty: true 
    command: sh -c "npm install && yarn add axios@0.19.2 bcryptjs@2.4.3 cors@2.8.5 dotenv@8.2.0 express@4.17.1 jsonwebtoken@8.5.1 moment@2.25.3 pg@8.0.3 nodemon@2.0.4 && yarn start"
    environment: 
      - NODE_ENV=development
      - PORT=5000
    environment: 
      POSTGRES_HOST: psql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank_account
    
    ports:
      - 5000:5000
    working_dir: /root/fullstack-banking-app/server
    depends_on: 
      - psql
    volumes:
      - ./server:/root/fullstack-banking-app/server:cached
  

  psql:
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank_account

volumes:
    banking-app-psql-data: